name: habithouse_io
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation & routing
  go_router: ^3.0.1

  # State management
  hooks_riverpod: ^1.0.3

  # Local Storage
  isar: ^2.1.4
  isar_flutter_libs: ^2.1.4

  # Backend SDK (data, auth, storage bucket)
  supabase_flutter: ^0.2.11

  # Localization
  easy_localization: ^3.0.0

  # Serialization & Immutable data types
  freezed_annotation: ^1.1.0

  # UI
  overlay_support: ^1.2.1
  flex_color_scheme: ^4.2.0
  google_fonts: ^2.3.1
  modal_bottom_sheet: ^2.0.0
  emoji_picker_flutter: ^1.1.2
  flex_color_picker: ^2.3.0
  reactive_date_range_picker: ^0.2.0

  # Notifications
  # TODO: implement local push notifications
  flutter_local_notifications: ^9.3.2

  # Deep linking
  # TODO: implement deep linking
  uni_links: ^0.5.1

  # Misc
  path_provider: ^2.0.8
  catcher: ^0.6.9
  logging: ^1.0.2
  sentry_flutter: ^6.2.2
  reactive_forms: ^11.0.1
  reactive_forms_annotations: ^0.3.2-beta
  built_collection: ^5.1.1
  dartx: ^1.0.0
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  isar_generator: ^2.1.4
  build_runner: ^2.1.7
  freezed: ^1.1.1
  reactive_forms_generator: ^0.9.5-beta
  flutter_gen_runner: ^4.1.6
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon.png"

dependency_overrides:
  path: ^1.8.1

flutter:
  uses-material-design: true

  assets:
    - assets/
